config/routes.rb
Rails.application.routes.draw do
  resources :lists, except: [ :edit, :update ] do
    resources :bookmarks, only: [ :new, :create]
  end
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :bookmark
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 5 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # has_one_attached :photo
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render new_list_path, status: :unprocessable_entity
    end
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_response
    api_key = ENV.fetch("OPENAI_API_KEY")
    engine = "text-davinci-003"
    prompt = "I have a meeting next weeek about concers related to RFP Evaluation, can you please provide a 3 objectives and an agenda"

    openai_client = OpenAI::Client.new(api_key: api_key, default_engine: engine)
    response = openai_client.completions(prompt: prompt, max_tokens: 4000, engine: engine)
    text = response.choices[0].text
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h4> <%= link_to "Go back home", lists_path  %> </h4>
<div class="container">
  <h1>Add a new bookmark:</h1>
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar-vanilla">
    <a class="navbar-vanilla-section" href="#">
      <img class="navbar-vanilla-logo" src="https://static.vecteezy.com/system/resources/previews/005/188/413/large_2x/cinema-logo-template-isolated-on-white-background-vector.jpg" alt="logo">
      <h2 class="navbar-vanilla-brand" >Cinemania</h2>
    </a>
    <div class="navbar-vanilla-section">
      <div class="navbar-vanilla-menu">
        <%= link_to "Add a new list", new_list_path %>
        <a href="#">Delete a list</a>
      </div>
      <div class="navbar-vanilla-profile">
        <%= image_tag('Screenshot 2023-05-11 at 7.05.05 pm.png', alt: 'Profile Picture') %>

        <ul>
          <li><a href="#">Profile</a></li>
          <li><a href="#">About us</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </div>
    </div>
</div>



  <div class="container mt-3">
    <h1>Your Lists:</h1>
    <% @lists.each do |list| %>
      <div class="card-pick">
        <%= list.photo.attached? ? cl_image_tag(list.photo.key) : image_tag('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU') %>
        <div class="card-pick-info">
          <h3><%= link_to list.name, list_path(list), class: "link-offset-2 link-underline link-underline-opacity-0" %></h3>
          <p class="black">It goes up when you hover over it.</p>
        </div>
      </div>
    <% end %>
  </div>

<%= generate_response() %>

app/views/lists/new.html.erb
<div class="navbar-vanilla">
    <a class="navbar-vanilla-section" href="#">
      <img class="navbar-vanilla-logo" src="https://static.vecteezy.com/system/resources/previews/005/188/413/large_2x/cinema-logo-template-isolated-on-white-background-vector.jpg" alt="logo">
      <h2 class="navbar-vanilla-brand" >Cinemania</h2>
    </a>
    <div class="navbar-vanilla-section">
      <div class="navbar-vanilla-menu">
        <%= link_to "Go back home", lists_path  %>
        <a href="#">Delete a list</a>
      </div>
      <div class="navbar-vanilla-profile">
        <%= image_tag('Screenshot 2023-05-11 at 7.05.05 pm.png', alt: 'Profile Picture') %>

        <ul>
          <li><a href="#">Profile</a></li>
          <li><a href="#">About us</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </div>
    </div>
</div>

<div class="container mt-5 col-6">
  <h1>Add a new list:</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="navbar-vanilla">
    <a class="navbar-vanilla-section" href="#">
      <img class="navbar-vanilla-logo" src="https://static.vecteezy.com/system/resources/previews/005/188/413/large_2x/cinema-logo-template-isolated-on-white-background-vector.jpg" alt="logo">
      <h2 class="navbar-vanilla-brand" >Cinemania</h2>
    </a>
    <div class="navbar-vanilla-section">
      <div class="navbar-vanilla-menu">
        <%= link_to "Add a new movie", new_list_bookmark_path(@list) %>
        <%= link_to "Go back home", lists_path  %>
      </div>
      <div class="navbar-vanilla-profile">
        <%= image_tag('Screenshot 2023-05-11 at 7.05.05 pm.png', alt: 'Profile Picture') %>

        <ul>
          <li><a href="#">Profile</a></li>
          <li><a href="#">About us</a></li>
          <li><a href="#">Login</a></li>
        </ul>
      </div>
    </div>
</div>

<div class="container mt-3">
  <h1><%= @list.name %>:</h1>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col mb-4">
        <div class="card-movie">
          <%= image_tag bookmark.movie.poster_url %>
          <div class="card-pick-info">
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.comment %></p>
            <h4>
              <%= link_to bookmark_path(bookmark),
              method: :delete,
              data: { turbo_confirm: "Are you sure?" },
              title: "Delete",
              "data-bs-toggle": "tooltip",
              "data-bs-placement": "top",
              "aria-label": "Delete" do %>
              <i class="fa-solid fa-trash fa-lg"></i>
              <% end %>
            </h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>